### Создание компании
POST http://127.0.0.1:8000/api/company/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwidXNlcl9pZCI6Mn0.ваш_токен_здесь
Content-Type: application/json

{
  "name": "ООО НаноБизнес",
  "inn": "123456789012"
}
