# Generated by Django 5.2.3 on 2025-07-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
