# Generated by Django 5.2.3 on 2025-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_company_options_product_supplier_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='inn',
            field=models.CharField(default=0, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
